import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* นำตัวแปรฟอนต์ และ Class สำหรับตกแต่งพื้นหลังมารวมกันที่ tag body */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-50 font-sans flex flex-col`}
      >
        <Navbar /> {/* ใส่ Navbar ไว้ด้านบนสุด */}
        {/* ให้ children (เนื้อหาของหน้าเว็บต่างๆ) อยู่ตรงนี้ */}
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
